In [1]:
# Importacion de librerias necesarias
import os
import gymnasium   #
import DemoC_RL   # Entorno personalizado
import numpy as np
import matplotlib.pyplot as plt
import stable_baselines3   # Biblioteca RL
import torch as th   # para modelo CNN
import torch.nn as nn
from gymnasium import spaces
from stable_baselines3.common.env_checker import check_env # Verificar el entorno
from stable_baselines3.common.vec_env import VecFrameStack, VecNormalize # Envoltorio para imagen
from stable_baselines3.sac.policies import MlpPolicy, CnnPolicy # Arquitectura de RN
from stable_baselines3 import A2C, TD3, DQN, DDPG, PPO, SAC, HER # algoritmo de entrenamiento
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
from stable_baselines3.common.utils import get_system_info
from stable_baselines3.common.noise import NormalActionNoise

from stable_baselines3.common.monitor import Monitor

from stable_baselines3.common.callbacks import BaseCallback
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.results_plotter import load_results, ts2xy
from stable_baselines3.common import results_plotter
#get_system_info(True)

OSError: [WinError 127] No se encontró el proceso especificado. Error loading "C:\Users\USUARIO\anaconda3\envs\IAGen\Lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.

In [2]:
# Clase para guardar el mejor modelo entrenado en base a las recompensas
class SaveOnBestTrainingRewardCallback(BaseCallback):
    """
    Callback for saving a model (the check is done every ``check_freq`` steps)
    based on the training reward (in practice, we recommend using ``EvalCallback``).

    :param check_freq: (int)
    :param log_dir: (str) Path to the folder where the model will be saved.
      It must contains the file created by the ``Monitor`` wrapper.
    :param verbose: (int)
    """

    def __init__(self, check_freq: int, log_dir: str, verbose=1):
        super().__init__(verbose)
        self.check_freq = check_freq
        self.log_dir = log_dir
        self.save_path = os.path.join(log_dir, "best_model")
        self.best_mean_reward = -np.inf

    def _init_callback(self) -> None:
        # Create folder if needed
        if self.save_path is not None:
            os.makedirs(self.save_path, exist_ok=True)

    def _on_step(self) -> bool:
        if self.n_calls % self.check_freq == 0:

            # Retrieve training reward
            x, y = ts2xy(load_results(self.log_dir), "timesteps")
            if len(x) > 0:
                # Mean training reward over the last 100 episodes
                mean_reward = np.mean(y[-100:])
                if self.verbose > 0:
                    print(f"Num timesteps: {self.num_timesteps}")
                    print(
                        f"Best mean reward: {self.best_mean_reward:.2f} - Last mean reward per episode: {mean_reward:.2f}"
                    )

                # New best model, you could save the agent here
                if mean_reward > self.best_mean_reward:
                    self.best_mean_reward = mean_reward
                    # Example for saving best model
                    if self.verbose > 0:
                        print(f"Saving new best model to {self.save_path}.zip")
                    self.model.save(self.save_path)

        return True

In [3]:
# Create log dir
log_dir = "./logs"
os.makedirs(log_dir, exist_ok=True)
# Inicializar el entorno
ENV_NAME = "DemoC_RL/TareaRL-v0"
#env = gymnasium.make(ENV_NAME) 
env = make_vec_env(ENV_NAME, n_envs=1, seed=1, monitor_dir=log_dir)
callback = SaveOnBestTrainingRewardCallback(check_freq=20, log_dir=log_dir, verbose=1)
# check_env(env, warn=True) # si funciona
# env = VecFrameStack(env, n_stack=4)

Conectado al servidor API remoto


In [4]:
policy_kwargs = dict(activation_fn=th.nn.ReLU, net_arch=dict(pi=[256, 512, 256], vf=[256, 512, 256]))

In [5]:
# Definir y entrenar el agente con A2C
model = A2C("MlpPolicy", env, gamma=0.99, policy_kwargs= policy_kwargs, verbose=1, device="auto", tensorboard_log='./A2C_tensorboard/')
model.learn(total_timesteps = 1000, callback=callback)
model.save("modeloA2C-1k") # Guardar modelo DRL

Using cuda device
Logging to ./A2C_tensorboard/A2C_1
--------------------------------------------------------------------
STEP:  1
Acciones:  [0.6478558  0.26972967 1.        ]
Distancia: 27.552  cm
--- RECOMPENSA TOTAL: -2.755 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  2
Acciones:  [ 0.43944964  0.38545585 -0.44723552]
Distancia: 27.258  cm
--- RECOMPENSA TOTAL: -2.726 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  3
Acciones:  [0.24862342 0.11055297 0.29628572]
Distancia: 27.303  cm
--- RECOMPENSA TOTAL: -2.730 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  4
Acciones:  [ 1.        -1.        -0.7612047]
Distancia: 27.472  cm
--- RECOMPENSA TOTAL: -2.747 --- 
[ 0.6        -0.05        0.03750008]
--------------------------------------------------------------------
STE

Distancia: 27.195  cm
--- RECOMPENSA TOTAL: -2.719 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  39
Acciones:  [0.6424906 0.679017  1.       ]
Distancia: 27.114  cm
--- RECOMPENSA TOTAL: -2.711 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  40
Acciones:  [-0.61152965  1.          0.22535883]
Distancia: 26.743  cm
--- RECOMPENSA TOTAL: -2.674 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  41
Acciones:  [-1.         -1.         -0.93648994]
Distancia: 26.988  cm
--- RECOMPENSA TOTAL: -2.699 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  42
Acciones:  [ 0.05953848 -0.13699171 -1.        ]
Distancia: 26.819  cm
--- RECOMPENSA TOTAL: -2.682 --- 
[ 0.6        -0.05        0.03750009]
------------------------

--------------------------------------------------------------------
STEP:  76
Acciones:  [-0.23076472 -0.7254045   0.65528977]
Distancia: 30.396  cm
--- RECOMPENSA TOTAL: -3.040 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  77
Acciones:  [-0.5879924   0.30174696  1.        ]
Distancia: 30.504  cm
--- RECOMPENSA TOTAL: -3.050 --- 
[ 0.6        -0.05        0.03748661]
--------------------------------------------------------------------
STEP:  78
Acciones:  [0.60464543 0.678228   0.0365289 ]
Distancia: 30.203  cm
--- RECOMPENSA TOTAL: -3.020 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  79
Acciones:  [-0.78336555 -1.          0.38600436]
Distancia: 30.749  cm
--- RECOMPENSA TOTAL: -3.075 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  80
Acciones:  [-0.22144985 -0.69970363 

Distancia: 28.881  cm
--- RECOMPENSA TOTAL: -2.888 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  114
Acciones:  [-0.505039   -0.5320429  -0.00513135]
Distancia: 29.117  cm
--- RECOMPENSA TOTAL: -2.912 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  115
Acciones:  [-1.          0.42349008 -0.86354446]
Distancia: 28.743  cm
--- RECOMPENSA TOTAL: -2.874 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  116
Acciones:  [ 0.44296297  0.37694335 -0.08979465]
Distancia: 28.552  cm
--- RECOMPENSA TOTAL: -2.855 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  117
Acciones:  [ 0.61968595 -0.6779586   0.56305534]
Distancia: 28.980  cm
--- RECOMPENSA TOTAL: -2.898 --- 
[ 0.6        -0.05        0.03750009]
--------------

Distancia: 25.957  cm
--- RECOMPENSA TOTAL: -2.596 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  151
Acciones:  [-1.         -0.28578776 -0.9130422 ]
Distancia: 25.926  cm
--- RECOMPENSA TOTAL: -2.593 --- 
[ 0.6        -0.05        0.03749893]
--------------------------------------------------------------------
STEP:  152
Acciones:  [-0.64872223  0.96733963  1.        ]
Distancia: 25.647  cm
--- RECOMPENSA TOTAL: -2.564 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  153
Acciones:  [ 1.  1. -1.]
Distancia: 25.003  cm
--- RECOMPENSA TOTAL: -2.500 --- 
[ 0.6        -0.05        0.03748661]
--------------------------------------------------------------------
STEP:  154
Acciones:  [ 0.37924254  0.92224807 -0.357637  ]
Distancia: 24.512  cm
--- RECOMPENSA TOTAL: -2.451 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------

--------------------------------------------------------------------
STEP:  188
Acciones:  [ 1.         -1.          0.44632173]
Distancia: 23.183  cm
--- RECOMPENSA TOTAL: -2.318 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  189
Acciones:  [ 0.79809195  0.42716476 -0.55878663]
Distancia: 22.913  cm
--- RECOMPENSA TOTAL: -2.291 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  190
Acciones:  [-1.         -0.4028345  -0.71473044]
Distancia: 23.034  cm
--- RECOMPENSA TOTAL: -2.303 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  191
Acciones:  [-0.3452421  -0.36975953 -0.615185  ]
Distancia: 23.157  cm
--- RECOMPENSA TOTAL: -2.316 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  192
Acciones:  [ 0.38666105 -1. 

--------------------------------------------------------------------
STEP:  225
Acciones:  [-1.         0.7967092 -1.       ]
Distancia: 19.170  cm
--- RECOMPENSA TOTAL: -1.917 --- 
[ 0.6        -0.05        0.03749319]
--------------------------------------------------------------------
STEP:  226
Acciones:  [ 0.47084045  0.5996997  -1.        ]
Distancia: 18.878  cm
--- RECOMPENSA TOTAL: -1.888 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  227
Acciones:  [-1.          0.6188015  -0.96842235]
Distancia: 18.624  cm
--- RECOMPENSA TOTAL: -1.862 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  228
Acciones:  [0.5061904  0.43482518 0.62617517]
Distancia: 18.372  cm
--- RECOMPENSA TOTAL: -1.837 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  229
Acciones:  [-0.9094061  1.        

Distancia: 16.896  cm
--- RECOMPENSA TOTAL: -1.690 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  263
Acciones:  [-0.08682502 -0.3060395  -1.        ]
Distancia: 17.195  cm
--- RECOMPENSA TOTAL: -1.720 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  264
Acciones:  [-1.        -0.6430368 -0.1233152]
Distancia: 17.607  cm
--- RECOMPENSA TOTAL: -1.761 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  265
Acciones:  [-0.14775647 -0.49264926 -0.8600006 ]
Distancia: 17.985  cm
--- RECOMPENSA TOTAL: -1.799 --- 
[ 0.6        -0.05        0.03750009]
--------------------------------------------------------------------
STEP:  266
Acciones:  [-0.21632639  1.         -0.61482364]
Distancia: 17.649  cm
--- RECOMPENSA TOTAL: -1.765 --- 
[ 0.6        -0.05        0.03750009]
-----------------

Distancia: 20.569  cm
--- RECOMPENSA TOTAL: -2.069 --- 
[ 0.61128086 -0.02552818  0.03750009]
--------------------------------------------------------------------
STEP:  300
Acciones:  [-0.77984035 -0.86774766 -0.19098979]
Distancia: 21.797  cm
--- RECOMPENSA TOTAL: -2.192 --- 
[ 0.6124132  -0.01712949  0.03750009]
--------------------------------------------------------------------
STEP:  301
Acciones:  [-0.6232876   1.          0.28415805]
Distancia: 22.213  cm
--- RECOMPENSA TOTAL: -2.235 --- 
[ 0.61362845 -0.00811626  0.03749949]
--------------------------------------------------------------------
STEP:  302
Acciones:  [-0.17920007 -0.1383503   0.91734654]
Distancia: 22.795  cm
--- RECOMPENSA TOTAL: -2.292 --- 
[ 6.1465037e-01 -5.3695380e-04  3.7500091e-02]
--------------------------------------------------------------------
STEP:  303
Acciones:  [-0.34907424 -1.         -0.43026853]
Distancia: 24.096  cm
--- RECOMPENSA TOTAL: -2.424 --- 
[0.61581033 0.00806658 0.03750009]
--------

Distancia: 50.981  cm
--- RECOMPENSA TOTAL: -5.114 --- 
[0.6545046  0.29505596 0.03750009]
--------------------------------------------------------------------
STEP:  338
Acciones:  [0.26347238 1.         0.5750188 ]
Distancia: 51.252  cm
--- RECOMPENSA TOTAL: -5.139 --- 
[0.65563697 0.30345467 0.03750009]
--------------------------------------------------------------------
STEP:  339
Acciones:  [ 0.12562905 -1.          1.        ]
Distancia: 52.337  cm
--- RECOMPENSA TOTAL: -5.245 --- 
[0.6567141  0.31144366 0.03750009]
--------------------------------------------------------------------
STEP:  340
Acciones:  [0.37735343 1.         0.5256753 ]
Distancia: 52.447  cm
--- RECOMPENSA TOTAL: -5.257 --- 
[0.65765315 0.31840843 0.03749935]
--------------------------------------------------------------------
STEP:  341
Acciones:  [-0.6924113  -1.          0.06050546]
Distancia: 53.780  cm
--- RECOMPENSA TOTAL: -5.392 --- 
[0.6587855  0.3268071  0.03750009]
-----------------------------------

Distancia: 81.237  cm
--- RECOMPENSA TOTAL: -8.138 --- 
[0.69725883 0.6121577  0.03750009]
--------------------------------------------------------------------
STEP:  376
Acciones:  [ 0.63020766  0.04060721 -0.67836756]
Distancia: 82.042  cm
--- RECOMPENSA TOTAL: -8.216 --- 
[0.6983912  0.6205564  0.03750009]
--------------------------------------------------------------------
STEP:  377
Acciones:  [ 0.950578    0.5969343  -0.18721984]
Distancia: 82.460  cm
--- RECOMPENSA TOTAL: -8.260 --- 
[0.6995512  0.6291599  0.03750009]
--------------------------------------------------------------------
STEP:  378
Acciones:  [-0.55212516 -0.05456232  0.13832687]
Distancia: 83.371  cm
--- RECOMPENSA TOTAL: -8.353 --- 
[0.7006836  0.63755864 0.03750009]
--------------------------------------------------------------------
STEP:  379
Acciones:  [-1.         1.         0.5034219]
Distancia: 83.870  cm
--- RECOMPENSA TOTAL: -8.401 --- 
[0.7018988  0.6465719  0.03749783]
--------------------------------

--------------------------------------------------------------------
STEP:  413
Acciones:  [-0.9102025  -0.9326378  -0.66062903]
Distancia: 112.006  cm
--- RECOMPENSA TOTAL: -11.217 --- 
[0.7409521  0.9362242  0.03750009]
--------------------------------------------------------------------
STEP:  414
Acciones:  [-0.30507424  0.66471857 -0.32192203]
Distancia: 112.626  cm
--- RECOMPENSA TOTAL: -11.277 --- 
[0.7421121  0.9448278  0.03750009]
--------------------------------------------------------------------
STEP:  415
Acciones:  [ 0.39501792  1.         -0.27588516]
Distancia: 112.987  cm
--- RECOMPENSA TOTAL: -11.313 --- 
[0.7432997  0.95363617 0.03750009]
--------------------------------------------------------------------
STEP:  416
Acciones:  [-0.82111603 -0.58061653 -0.12873127]
Distancia: 114.234  cm
--- RECOMPENSA TOTAL: -11.440 --- 
[0.74451494 0.9626494  0.03750001]
--------------------------------------------------------------------
STEP:  417
Acciones:  [-1.          0.44852

Distancia: 144.095  cm
--- RECOMPENSA TOTAL: -14.426 --- 
[0.7830987  1.2488194  0.03750009]
--------------------------------------------------------------------
STEP:  451
Acciones:  [-0.8694397 -0.9120765  0.7191676]
Distancia: 145.484  cm
--- RECOMPENSA TOTAL: -14.565 --- 
[0.7843416  1.2580374  0.03750009]
--------------------------------------------------------------------
STEP:  452
Acciones:  [-0.44222516  0.81827956 -1.        ]
Distancia: 146.096  cm
--- RECOMPENSA TOTAL: -14.622 --- 
[0.78547394 1.2664361  0.03750009]
--------------------------------------------------------------------
STEP:  453
Acciones:  [ 0.10344262 -1.          1.        ]
Distancia: 147.278  cm
--- RECOMPENSA TOTAL: -14.742 --- 
[0.7865787  1.27463    0.03750009]
--------------------------------------------------------------------
STEP:  454
Acciones:  [ 0.46775612 -0.19804569 -0.7698785 ]
Distancia: 148.218  cm
--- RECOMPENSA TOTAL: -14.838 --- 
[0.7877387  1.2832335  0.03750009]
----------------------

--- RECOMPENSA TOTAL: -17.695 --- 
[0.8258805  1.566126   0.03750009]
--------------------------------------------------------------------
STEP:  488
Acciones:  [ 1.          1.         -0.01076251]
Distancia: 177.058  cm
--- RECOMPENSA TOTAL: -17.720 --- 
[0.82706815 1.5749344  0.03750009]
--------------------------------------------------------------------
STEP:  489
Acciones:  [-0.83032423 -1.         -0.04336727]
Distancia: 178.498  cm
--- RECOMPENSA TOTAL: -17.866 --- 
[0.8282282  1.5835379  0.03750009]
--------------------------------------------------------------------
STEP:  490
Acciones:  [0.4497805  0.8614222  0.92352414]
Distancia: 178.806  cm
--- RECOMPENSA TOTAL: -17.897 --- 
[0.82938814 1.5921415  0.03750009]
--------------------------------------------------------------------
STEP:  491
Acciones:  [-0.0460972   0.43832237  0.55364436]
Distancia: 179.422  cm
--- RECOMPENSA TOTAL: -17.958 --- 
[0.8305206  1.6005402  0.03750009]
---------------------------------------------

Distancia: 209.441  cm
--- RECOMPENSA TOTAL: -20.960 --- 
[0.8660938  1.8643819  0.03750009]
--------------------------------------------------------------------
STEP:  523
Acciones:  [-0.12989055  0.18751016 -0.07947723]
Distancia: 210.126  cm
--- RECOMPENSA TOTAL: -21.027 --- 
[0.86708814 1.8717563  0.03750009]
--------------------------------------------------------------------
STEP:  524
Acciones:  [-1.          0.2841274   0.59835386]
Distancia: 210.915  cm
--- RECOMPENSA TOTAL: -21.106 --- 
[0.8682481  1.8803599  0.03750009]
--------------------------------------------------------------------
STEP:  525
Acciones:  [0.7664912 0.2307257 0.8561003]
Distancia: 211.541  cm
--- RECOMPENSA TOTAL: -21.169 --- 
[0.8694357  1.8891683  0.03750009]
--------------------------------------------------------------------
STEP:  526
Acciones:  [ 1.  1. -1.]
Distancia: 211.790  cm
--- RECOMPENSA TOTAL: -21.193 --- 
[0.8705129  1.8971573  0.03750009]
-------------------------------------------------

--------------------------------------------------------------------
STEP:  560
Acciones:  [-0.05905706  1.         -1.        ]
Distancia: 238.045  cm
--- RECOMPENSA TOTAL: -23.821 --- 
[0.90973186 2.1880388  0.03750009]
--------------------------------------------------------------------
STEP:  561
Acciones:  [-0.41349378  0.9393697  -1.        ]
Distancia: 238.504  cm
--- RECOMPENSA TOTAL: -23.865 --- 
[0.9107814  2.195823   0.03750006]
--------------------------------------------------------------------
STEP:  562
Acciones:  [-1.         -0.42260128 -0.60991085]
Distancia: 239.671  cm
--- RECOMPENSA TOTAL: -23.981 --- 
[0.91191375 2.2042215  0.03750005]
--------------------------------------------------------------------
STEP:  563
Acciones:  [ 0.15636857 -1.         -0.2349935 ]
Distancia: 240.989  cm
--- RECOMPENSA TOTAL: -24.111 --- 
[0.9130185  2.2124155  0.03750009]
--------------------------------------------------------------------
STEP:  564
Acciones:  [ 0.6947112   0.41844

--------------------------------------------------------------------
STEP:  597
Acciones:  [ 1.  1. -1.]
Distancia: 604.435  cm
--- RECOMPENSA TOTAL: -106.388 --- 
[  0.9521858   2.9515905 -12.626748 ]
--------------------------------------------------------------------
STEP:  598
Acciones:  [ 0.10840976 -0.6420665   0.37216642]
Distancia: 5032.380  cm
--- RECOMPENSA TOTAL: -619.147 --- 
[  0.95312274   3.529866   -69.17689   ]
--------------------------------------------------------------------
STEP:  599
Acciones:  [ 1.         -0.64067435 -0.05549594]
Distancia: 13793.994  cm
--- RECOMPENSA TOTAL: -1595.406 --- 
[   0.95405966    4.1081414  -171.07375   ]
--------------------------------------------------------------------
STEP:  600
Acciones:  [-1.  1. -1.]
Distancia: 27617.146  cm
--- RECOMPENSA TOTAL: -3064.082 --- 
[   0.95501834    4.6998653  -322.28116   ]
--------------------------------------------------------------------
STEP:  601
Acciones:  [ 0.3697958 -0.7978496 -1.     

--- RECOMPENSA TOTAL: -10106.535 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  632
Acciones:  [ 1.         -0.15083605 -0.24783945]
Distancia: 101065.224  cm
--- RECOMPENSA TOTAL: -10106.522 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  633
Acciones:  [-1.          1.         -0.43073982]
Distancia: 101065.007  cm
--- RECOMPENSA TOTAL: -10106.501 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  634
Acciones:  [-0.88572615  1.         -0.0968694 ]
Distancia: 101064.955  cm
--- RECOMPENSA TOTAL: -10106.496 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  635
Acciones:  [ 0.47973442 -0.48364115 -1.        ]
Distancia: 101064.456  cm
--- RECOMPENSA TOTAL: -10106.446 --- 
[ 

Distancia: 101063.294  cm
--- RECOMPENSA TOTAL: -10106.329 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  667
Acciones:  [1.         0.62963074 1.        ]
Distancia: 101063.793  cm
--- RECOMPENSA TOTAL: -10106.379 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  668
Acciones:  [ 1.         -0.10558644 -1.        ]
Distancia: 101063.292  cm
--- RECOMPENSA TOTAL: -10106.329 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  669
Acciones:  [-0.34181935  0.5953323   1.        ]
Distancia: 101063.791  cm
--- RECOMPENSA TOTAL: -10106.379 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  670
Acciones:  [-0.1342388  -0.34127492  0.86465144]
Distancia: 101064.225  cm
--- RECOMPENSA TO

--------------------------------------------------------------------
STEP:  701
Acciones:  [-1.         -0.86362106  0.4015786 ]
Distancia: 101061.514  cm
--- RECOMPENSA TOTAL: -10106.151 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  702
Acciones:  [-1.        -0.4541928  1.       ]
Distancia: 101062.016  cm
--- RECOMPENSA TOTAL: -10106.202 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  703
Acciones:  [ 0.20236471  1.         -0.33610874]
Distancia: 101061.842  cm
--- RECOMPENSA TOTAL: -10106.184 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  704
Acciones:  [-0.70552385  1.          0.30202866]
Distancia: 101061.991  cm
--- RECOMPENSA TOTAL: -10106.199 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
-------------------------------------------

Distancia: 101057.002  cm
--- RECOMPENSA TOTAL: -10105.700 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  736
Acciones:  [-0.237734    1.          0.31779388]
Distancia: 101057.158  cm
--- RECOMPENSA TOTAL: -10105.716 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  737
Acciones:  [0.70495665 0.54779965 0.18412441]
Distancia: 101057.248  cm
--- RECOMPENSA TOTAL: -10105.725 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  738
Acciones:  [ 0.3367778   1.         -0.21479276]
Distancia: 101057.141  cm
--- RECOMPENSA TOTAL: -10105.714 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  739
Acciones:  [-0.7392858  0.4151813  1.       ]
Distancia: 101057.640  cm
--- RECOMPENSA TOTAL

--------------------------------------------------------------------
STEP:  770
Acciones:  [0.52110755 1.         0.5814254 ]
Distancia: 101056.896  cm
--- RECOMPENSA TOTAL: -10105.690 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  771
Acciones:  [-1.          0.64788353 -0.67028666]
Distancia: 101056.558  cm
--- RECOMPENSA TOTAL: -10105.656 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  772
Acciones:  [-0.216914   1.         0.2257312]
Distancia: 101056.665  cm
--- RECOMPENSA TOTAL: -10105.666 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  773
Acciones:  [-1. -1. -1.]
Distancia: 101056.168  cm
--- RECOMPENSA TOTAL: -10105.617 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
S

Distancia: 101051.229  cm
--- RECOMPENSA TOTAL: -10105.123 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  805
Acciones:  [-0.9716825   0.21054631 -1.        ]
Distancia: 101050.729  cm
--- RECOMPENSA TOTAL: -10105.073 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  806
Acciones:  [-0.8863261 -1.         0.3771118]
Distancia: 101050.921  cm
--- RECOMPENSA TOTAL: -10105.092 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  807
Acciones:  [0.63320947 0.45623854 0.40586072]
Distancia: 101051.121  cm
--- RECOMPENSA TOTAL: -10105.112 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  808
Acciones:  [-1.         -0.31283945  0.8561992 ]
Distancia: 101051.550  cm
--- RECOMPENSA TOTAL

--------------------------------------------------------------------
STEP:  839
Acciones:  [-0.73185354 -1.         -0.14845982]
Distancia: 101050.393  cm
--- RECOMPENSA TOTAL: -10105.039 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  840
Acciones:  [ 0.34122866  1.         -0.98295385]
Distancia: 101049.901  cm
--- RECOMPENSA TOTAL: -10104.990 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  841
Acciones:  [-0.5547389  -0.4286049   0.49590364]
Distancia: 101050.147  cm
--- RECOMPENSA TOTAL: -10105.015 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  842
Acciones:  [-1.         -0.48779237  1.        ]
Distancia: 101050.649  cm
--- RECOMPENSA TOTAL: -10105.065 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
----------------------------------------

Distancia: 101052.997  cm
--- RECOMPENSA TOTAL: -10105.300 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  874
Acciones:  [ 1.         -1.          0.14723645]
Distancia: 101053.073  cm
--- RECOMPENSA TOTAL: -10105.307 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  875
Acciones:  [ 0.4834368   0.23540549 -0.08572277]
Distancia: 101053.030  cm
--- RECOMPENSA TOTAL: -10105.303 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  876
Acciones:  [-0.5763846  -1.          0.14378254]
Distancia: 101053.100  cm
--- RECOMPENSA TOTAL: -10105.310 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  877
Acciones:  [-1.         1.        -0.9035821]
Distancia: 101052.646  cm
--- RECOMPENSA TO

Distancia: 101056.068  cm
--- RECOMPENSA TOTAL: -10105.607 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  909
Acciones:  [-0.7475568  1.         0.659516 ]
Distancia: 101056.395  cm
--- RECOMPENSA TOTAL: -10105.639 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  910
Acciones:  [-0.19873129  1.          0.17127201]
Distancia: 101056.477  cm
--- RECOMPENSA TOTAL: -10105.648 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  911
Acciones:  [ 0.4070196  -0.06219627  1.        ]
Distancia: 101056.978  cm
--- RECOMPENSA TOTAL: -10105.698 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  912
Acciones:  [0.8028702  0.5061899  0.61475164]
Distancia: 101057.281  cm
--- RECOMPENSA TOTAL

--------------------------------------------------------------------
STEP:  943
Acciones:  [ 0.05828139 -0.01076344  0.8896479 ]
Distancia: 101053.629  cm
--- RECOMPENSA TOTAL: -10105.363 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  944
Acciones:  [-1.        -0.9699459  1.       ]
Distancia: 101054.133  cm
--- RECOMPENSA TOTAL: -10105.413 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  945
Acciones:  [ 0.42479235 -0.1356047  -0.7212767 ]
Distancia: 101053.774  cm
--- RECOMPENSA TOTAL: -10105.377 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  946
Acciones:  [ 0.11263943 -0.6240554  -1.        ]
Distancia: 101053.275  cm
--- RECOMPENSA TOTAL: -10105.328 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
-------------------------------------------

Distancia: 101046.783  cm
--- RECOMPENSA TOTAL: -10104.678 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  978
Acciones:  [1.         0.22019434 0.98884183]
Distancia: 101047.276  cm
--- RECOMPENSA TOTAL: -10104.728 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  979
Acciones:  [-1.  1.  1.]
Distancia: 101047.774  cm
--- RECOMPENSA TOTAL: -10104.777 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  980
Acciones:  [-0.42452493  1.         -1.        ]
Distancia: 101047.271  cm
--- RECOMPENSA TOTAL: -10104.727 --- 
[ 9.5774192e-01  6.3808994e+00 -1.0108930e+03]
--------------------------------------------------------------------
STEP:  981
Acciones:  [-0.6138444  -0.06781127  1.        ]
Distancia: 101047.772  cm
--- RECOMPENSA TOTAL: -10104.777 --- 
[ 9

In [10]:
# Graficar Curva de Aprendizaje obtenida durante entrenamiento
# Helper from the library
results_plotter.plot_results(
    [log_dir], 1000, results_plotter.X_TIMESTEPS, "Datos de entrenamiento"
)
def moving_average(values, window):
    """
    Smooth values by doing a moving average
    :param values: (numpy array)
    :param window: (int)
    :return: (numpy array)
    """
    weights = np.repeat(1.0, window) / window
    return np.convolve(values, weights, "valid")


def plot_results(log_folder, title="Curva de aprendizaje"):
    """
    plot the results

    :param log_folder: (str) the save location of the results to plot
    :param title: (str) the title of the task to plot
    """
    x, y = ts2xy(load_results(log_folder), "timesteps")
    y = moving_average(y, window=100)
    # Truncate x
    x = x[len(x) - len(y) :]

    fig = plt.figure(title)
    plt.figure(figsize=(8,2), dpi=500)
    plt.plot(x, y)
    plt.grid()
    plt.xlabel("Number of Timesteps",fontsize=7)
    plt.ylabel("Rewards",fontsize=7)
    plt.title(title + " Smoothed",fontsize=8)
    plt.tick_params(axis='both', which='major', labelsize=7)
    plt.show()


plot_results(log_dir)



IndexError: index -1 is out of bounds for axis 0 with size 0

<Figure size 800x200 with 0 Axes>